name: mobitra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  flutter_bloc: 9.1.1
  equatable: ^2.0.7
  mocktail: ^1.0.4   
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/MobitraLogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/MobitraLogo.png"
